// Turns assets/src originals into AVIF/WebP/JPEG at responsive widths in public/img,
// writes src/generated/images.ts, and builds public/og.jpg.
import sharp from 'sharp';
import { mkdir, writeFile, access } from 'node:fs/promises';

const exists = async (p) => access(p).then(() => true, () => false);

// key -> source, widths, optional blur (for "video coming soon" posters that must not be readable)
const jobs = {
  hero:         { src: 'assets/src/hero.jpeg',          widths: [480, 640, 800, 1280] },
  casual:       { src: 'assets/src/casual.jpeg',        widths: [480, 960] },
  wall:         { src: 'assets/src/wall.png',           widths: [720, 1200, 1686] },
  bengaluruRun: { src: 'assets/src/bengaluru-run.png',  widths: [640, 1080, 1440] },
  posterInvoice:   { src: 'assets/src/frame-invoice.jpg',   widths: [640, 1280] },
  posterDashboard: { src: 'assets/src/frame-dashboard.jpg', widths: [640, 1280] },
};

await mkdir('public/img', { recursive: true });
await mkdir('src/generated', { recursive: true });
const out = {};

for (const [key, job] of Object.entries(jobs)) {
  // If prep-video.mjs has extracted a frame, use it sharp; otherwise blur the Screen Studio thumbnail.
  let src = job.src, blur = job.blur ?? 0, pending = false;
  if (job.frame) {
    if (await exists(job.frame)) { src = job.frame; blur = 0; }
    else pending = true;
  }
  let base = sharp(src).rotate();
  const meta = await base.metadata();
  out[key] = { width: meta.width, height: meta.height, avif: [], webp: [], jpg: '', pending };
  for (const w of job.widths) {
    let r = base.clone().resize({ width: w, withoutEnlargement: true });
    if (blur) r = r.blur(blur * (w / 1280));
    await r.clone().avif({ quality: 55, effort: 5 }).toFile(`public/img/${key}-${w}.avif`);
    await r.clone().webp({ quality: 80 }).toFile(`public/img/${key}-${w}.webp`);
    out[key].avif.push(w); out[key].webp.push(w);
  }
  let j = base.clone().resize({ width: job.widths.at(-1), withoutEnlargement: true });
  if (blur) j = j.blur(blur);
  await j.jpeg({ quality: 82, mozjpeg: true }).toFile(`public/img/${key}.jpg`);
  out[key].jpg = `/img/${key}.jpg`;
  console.log(`${key.padEnd(16)} ${meta.width}x${meta.height}  widths ${job.widths.join('/')}${blur ? '  (blurred placeholder)' : ''}`);
}


await writeFile('src/generated/images.ts',
  `// Generated by scripts/prep-images.mjs. Do not edit.\nexport const images = ${JSON.stringify(out, null, 2)} as const;\nexport type ImageKey = keyof typeof images;\n`);
console.log('wrote src/generated/images.ts');
